name: dart_webrtc
description: Use the dart/js library to re-wrap the webrtc js interface of the browser, to adapted common browsers.
version: 1.4.9
homepage: https://github.com/flutter-webrtc/dart-webrtc

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  js: ">0.6.0 <0.8.0"
  logging: ^1.1.0
  meta: ^1.8.0
  platform_detect: ^2.0.7
  synchronized: ^3.0.0+3
  web: ^1.0.0
  webrtc_interface: ^1.2.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers:
  http: ">0.13.0 <1.3.0"
  import_sorter: ^4.6.0
  pedantic: ^1.9.0
  protoo_client: ^0.3.0
  test: ^1.15.4
