name: dart_webrtc
description: Use the dart/js library to re-wrap the webrtc js interface of the browser, to adapted common browsers.
version: 1.0.11
homepage: https://github.com/flutter-webrtc/dart-webrtc

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  platform_detect: ^2.0.7
  webrtc_interface: ^1.0.10

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  http: ^0.13.3
  import_sorter: ^4.6.0
  pedantic: ^1.9.0
  protoo_client: ^0.3.0
  test: ^1.15.4
